import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/admin";
import { adminClient, seedIfEmpty } from "@/lib/catalog";

export async function GET(request: Request) {
  const unauthorized = requireAdmin(request);
  if (unauthorized) return unauthorized;
  const admin = adminClient();
  if (!admin) return NextResponse.json({ error: "Supabase not configured" }, { status: 500 });

  try {
    await seedIfEmpty();
  } catch (seedError) {
    return NextResponse.json(
      { error: seedError instanceof Error ? seedError.message : "Seed failed" },
      { status: 500 },
    );
  }
  const { data, error } = await admin
    .from("products")
    .select("*")
    .order("created_at", { ascending: false });
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ products: data });
}

export async function POST(request: Request) {
  const unauthorized = requireAdmin(request);
  if (unauthorized) return unauthorized;
  const admin = adminClient();
  if (!admin) return NextResponse.json({ error: "Supabase not configured" }, { status: 500 });

  const body = await request.json();
  if (!body.name || body.price === undefined || !body.category) {
    return NextResponse.json(
      { error: "name, price, and category are required" },
      { status: 400 },
    );
  }
  // The id is generated by Postgres (uuid primary key).
  const row = {
    name: body.name,
    category: body.category,
    // "Sale price" filled in → it becomes the selling price, regular price shows struck through.
    price: body.salePrice ? Number(body.salePrice) : Number(body.price),
    compare_at_price: body.salePrice ? Number(body.price) : null,
    description: body.description ?? "",
    features: body.features ?? [],
    image: body.image || null,
    images: body.images ?? [],
    // Rating and review_count are system-computed from the reviews table.
    rating: 0,
    review_count: 0,
    stock: Number(body.stock ?? 10),
    // CJ source ids ride inside the shipping jsonb (no schema change needed).
    shipping: body.cj ? { ...(body.shipping ?? {}), cj: body.cj } : (body.shipping ?? null),
    new_arrival: body.newArrival ?? true,
    date_added: new Date().toISOString().slice(0, 10),
  };
  const { data, error } = await admin.from("products").insert(row).select().single();
  if (error) return NextResponse.json({ error: error.message }, { status: 400 });
  if (body.aliexpressUrl) {
    // Separate update so an older table without the column can't fail the insert.
    await admin
      .from("products")
      .update({ aliexpress_url: body.aliexpressUrl })
      .eq("id", data.id);
  }
  return NextResponse.json({ product: data });
}

export async function PUT(request: Request) {
  const unauthorized = requireAdmin(request);
  if (unauthorized) return unauthorized;
  const admin = adminClient();
  if (!admin) return NextResponse.json({ error: "Supabase not configured" }, { status: 500 });

  const body = await request.json();
  if (!body.id) return NextResponse.json({ error: "id is required" }, { status: 400 });
  const update = {
    name: body.name,
    category: body.category,
    price: body.salePrice ? Number(body.salePrice) : Number(body.price),
    compare_at_price: body.salePrice ? Number(body.price) : null,
    description: body.description ?? "",
    features: body.features ?? [],
    image: body.image || null,
    images: body.images ?? [],
    // rating/review_count intentionally omitted — computed from real
    // reviews; editing a product must never reset them.
    stock: Number(body.stock ?? 10),
    ...(body.shipping !== undefined && {
      shipping: body.cj ? { ...(body.shipping ?? {}), cj: body.cj } : body.shipping,
    }),
  };
  const { data, error } = await admin
    .from("products")
    .update(update)
    .eq("id", body.id)
    .select()
    .single();
  if (error) return NextResponse.json({ error: error.message }, { status: 400 });
  // Only overwrite the supplier URL with a real value — a blank form field
  // must never erase it (that's how the Moon Lamp lost its URL).
  if (body.aliexpressUrl) {
    await admin
      .from("products")
      .update({ aliexpress_url: body.aliexpressUrl })
      .eq("id", body.id);
  }
  return NextResponse.json({ product: data });
}

export async function DELETE(request: Request) {
  const unauthorized = requireAdmin(request);
  if (unauthorized) return unauthorized;
  const admin = adminClient();
  if (!admin) return NextResponse.json({ error: "Supabase not configured" }, { status: 500 });

  const { searchParams } = new URL(request.url);
  const id = searchParams.get("id");
  if (!id) return NextResponse.json({ error: "id is required" }, { status: 400 });
  // The live reviews FK has no ON DELETE CASCADE — clear reviews first.
  await admin.from("reviews").delete().eq("product_id", id);
  // Remove rehosted images from storage (product-images/{id}/*).
  const { data: stored } = await admin.storage.from("product-images").list(id);
  if (stored && stored.length > 0) {
    await admin.storage
      .from("product-images")
      .remove(stored.map((file) => `${id}/${file.name}`));
  }
  const { error } = await admin.from("products").delete().eq("id", id);
  if (error) return NextResponse.json({ error: error.message }, { status: 400 });
  return NextResponse.json({ ok: true });
}
