import { createClient } from "@supabase/supabase-js";
import { products as seedProducts, type Product } from "@/lib/products";

/**
 * Server-side catalog backed by the Supabase `products` table, seeded from
 * the static catalog in lib/products.ts. Falls back to the static list when
 * the table is missing or empty so the storefront never goes blank.
 */

type ProductRow = {
  id: string;
  name: string;
  category: string;
  price: number;
  compare_at_price: number | null;
  description: string;
  features: string[];
  image: string | null;
  images: string[];
  variants: Product["variants"] | null;
  rating: number;
  review_count: number;
  reviews: Product["reviews"] | null;
  stock: number;
  shipping: Product["shipping"] | null;
  best_seller: boolean;
  new_arrival: boolean;
  deal: boolean;
  trending: boolean;
  date_added: string | null;
  sold_count?: number | null;
};

export function rowToProduct(row: ProductRow): Product {
  return {
    id: row.id,
    name: row.name,
    category: row.category,
    price: Number(row.price),
    compareAtPrice: row.compare_at_price ? Number(row.compare_at_price) : undefined,
    description: row.description,
    features: row.features ?? [],
    image: row.image ?? undefined,
    images: row.images ?? [],
    variants: row.variants ?? undefined,
    rating: Number(row.rating),
    reviewCount: row.review_count,
    reviews: row.reviews ?? undefined,
    shipping: row.shipping ?? undefined,
    inStock: row.stock > 0,
    bestSeller: row.best_seller,
    newArrival: row.new_arrival,
    deal: row.deal,
    trending: row.trending,
    dateAdded: row.date_added ?? undefined,
    soldCount: row.sold_count ?? undefined,
  };
}

/**
 * Builds an insert row. The id is intentionally omitted — the table's uuid
 * primary key is generated by Postgres, so slugs from the static catalog
 * never reach the database.
 */
export function productToRow(
  product: Product,
  stock: number,
): Omit<ProductRow, "id" | "created_at"> {
  return {
    name: product.name,
    category: product.category,
    price: product.price,
    compare_at_price: product.compareAtPrice ?? null,
    description: product.description,
    features: product.features,
    image: product.image ?? null,
    images: product.images ?? [],
    variants: product.variants ?? null,
    rating: product.rating,
    review_count: product.reviewCount,
    reviews: product.reviews ?? null,
    stock,
    shipping: product.shipping ?? null,
    best_seller: product.bestSeller ?? false,
    new_arrival: product.newArrival ?? false,
    deal: product.deal ?? false,
    trending: product.trending ?? false,
    date_added: product.dateAdded ?? null,
  };
}

export function adminClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) return null;
  return createClient(url, serviceKey, { db: { schema: "public" } });
}

/** Seeds the products table from the static catalog if it's empty. */
export async function seedIfEmpty(): Promise<void> {
  const admin = adminClient();
  if (!admin) return;
  const { count, error } = await admin
    .from("products")
    .select("id", { head: true, count: "exact" });
  if (error || (count ?? 0) > 0) return;
  const { error: insertError } = await admin
    .from("products")
    .insert(seedProducts.map((product) => productToRow(product, 25)));
  if (insertError) {
    console.error("Catalog seed failed:", insertError.message);
    throw new Error(`Catalog seed failed: ${insertError.message}`);
  }
}

export async function getCatalog(): Promise<Product[]> {
  const admin = adminClient();
  if (!admin) return seedProducts;
  const { data, error } = await admin
    .from("products")
    .select("*")
    .order("created_at", { ascending: true });
  if (error || !data || data.length === 0) {
    if (error) console.error("Catalog fetch failed, using static seed:", error.message);
    return seedProducts;
  }
  return data.map((row) => rowToProduct(row as ProductRow));
}

export async function getCatalogProduct(id: string): Promise<Product | undefined> {
  const catalog = await getCatalog();
  return catalog.find((product) => product.id === id);
}
